In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
tensor_zero_d.ndim

0

In [3]:
tensor_zero_d.shape

TensorShape([])

In [4]:
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2, 0, 3, 8, 90])
tensor_one_d.ndim

1

In [7]:
print(tensor_one_d)

tf.Tensor([ 2  0  3  8 90], shape=(5,), dtype=int32)


In [8]:
tensor_one_d.shape

TensorShape([5])

In [9]:
tensor_one_d

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  0,  3,  8, 90], dtype=int32)>

In [10]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
tensor_two_d.ndim

2

In [11]:
tensor_two_d

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

In [12]:
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [13]:
tensor_two_d.shape

TensorShape([4, 3])

In [14]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
     [3, 5, -1]],

    [[10, 2, 0],
     [1, 0, 2]],

    [[5, 8, 0],
     [2, 7, 0]],

    [[2, 1, 9],
     [4, -3, 32]]
])

tensor_three_d


<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0]],

       [[ 2,  1,  9],
        [ 4, -3, 32]]], dtype=int32)>

In [15]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [16]:
tensor_three_d.ndim

3

In [17]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [18]:
tensor_four_d = tf.constant([

[
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

],

[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],

],

[
    [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,3,0]],

    [[22,1,9],
    [44,-320,32]],

],

])

tensor_four_d

<tf.Tensor: shape=(3, 4, 2, 3), dtype=int32, numpy=
array([[[[   1,    2,    0],
         [   3,    5,   -1]],

        [[  10,    2,    0],
         [   1,    0,    2]],

        [[   5,    8,    0],
         [   2,    7,    0]],

        [[   2,    1,    9],
         [   4,   -3,   32]]],


       [[[  13,   26,    0],
         [   3,    5,  -12]],

        [[  10,    2,    0],
         [   1,    0,   23]],

        [[   5,    8,    0],
         [   2,   73,    0]],

        [[   2,    1,    9],
         [   4,  -30,   32]]],


       [[[ 103,   26,    0],
         [   3,   50,  -12]],

        [[ 100,    2,    0],
         [   1,    0,   23]],

        [[   5,   28,    0],
         [   2,    3,    0]],

        [[  22,    1,    9],
         [  44, -320,   32]]]], dtype=int32)>

In [19]:
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [20]:
tensor_four_d.ndim

4

In [21]:
tensor_four_d.shape

TensorShape([3, 4, 2, 3])

In [22]:
tensor_one_d = tf.constant([2, 0, 3, 8, 90], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0.  3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [23]:
tensor_string = tf.constant(["hello world", "hi"])

tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello world', b'hi'], dtype=object)>

In [24]:
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [25]:
tensor_string.shape

TensorShape([2])

In [26]:
tensor_string.ndim

1

In [27]:
import numpy as np

In [28]:
np_array = np.array([1, 2, 3, 4])
np_array

array([1, 2, 3, 4])

In [29]:
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [30]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [31]:
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [32]:
eye_tensor.shape

TensorShape([3, 3])

In [33]:
eye_tensor.ndim

2

In [34]:
print(3 * eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [35]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [36]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[4,],
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[ True False False]
  [False  True False]
  [False False  True]]

 [[ True False False]
  [False  True False]
  [False False  True]]

 [[ True False False]
  [False  True False]
  [False False  True]]

 [[ True False False]
  [False  True False]
  [False False  True]]], shape=(4, 3, 3), dtype=bool)


In [37]:
fill_tensor = tf.fill(
    [3, 4], 9, name=None
)
print(fill_tensor)

tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(3, 4), dtype=int32)


In [38]:
ones_tensor = tf.ones(
    [3, 4],
    dtype = tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [39]:
ones_tensor = tf.ones(
    [3, 4],
    dtype = tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [40]:
zeros_tensor = tf.zeros(
    [3, 2],
    dtype = tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [41]:
print(tensor_three_d.shape)

(4, 2, 3)


In [42]:
t = tf.constant([[[1, 1, 1, 1], [2, 2, 2, 2]], [[3, 3, 3, 3], [4, 4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [43]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=0.0,
    stddev=100.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[  -4.242675  -14.04282 ]
 [-153.28612   -38.495495]
 [ -96.81511   108.05882 ]], shape=(3, 2), dtype=float32)


In [44]:
random_tensor = tf.random.uniform(
    [3, 2],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[70.96098  40.506744]
 [91.09771  60.2131  ]
 [23.237288 70.90092 ]], shape=(3, 2), dtype=float32)


In [45]:
t = tf.constant([[[1, 1, 1, 1], [2, 2, 2, 2]], [[3, 3, 3, 3], [4, 4, 4, 4]]])
tf.size(t)


<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [46]:
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# **INDEXING**

In [47]:
tensor_index = tf.constant([2, 3, 4, 5, 5])
print(tensor_index[3])

tf.Tensor(5, shape=(), dtype=int32)


In [48]:
tensor_index[1]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [49]:
tensor_index[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [50]:
tensor_indexed = tf.constant([2, 4, 9, 0, 4, 5, 6, 7])

In [51]:
tensor_indexed[3:7]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 4, 5, 6], dtype=int32)>

In [52]:
a = tf.constant([
    [1, 5, 1],
    [7, 3, 0],
])

print(tf.transpose(a))

tf.Tensor(
[[1 7]
 [5 3]
 [1 0]], shape=(3, 2), dtype=int32)


In [53]:
a.shape

TensorShape([2, 3])

In [54]:
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [55]:
b = tf.constant([
    [3, 1, 9],
    [0, 1, 7],
    [1, 5, 1]
])

print(tf.linalg.matmul(a, b))

tf.Tensor(
[[ 4 11 45]
 [21 10 84]], shape=(2, 3), dtype=int32)


In [56]:
a@tf.transpose(b)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[17, 12, 27],
       [24,  3, 22]], dtype=int32)>

In [57]:
a@b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 11, 45],
       [21, 10, 84]], dtype=int32)>

In [58]:
tf.linalg.matmul(a, b, transpose_b=True)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[17, 12, 27],
       [24,  3, 22]], dtype=int32)>

In [59]:
a = tf.constant(
    [[[1, 0],
      [2, 1],
      [3, -1]],
     [[0, 2],
      [1, -1],
      [2, 3]],
     [[1, 2],
      [0, 1],
      [1, 1]],
     [[2, 0],
      [1, 1],
      [0, -1]]]
)

b = tf.constant(
    [[[1, 2, 0],
      [3, 5, -1]],
     [[10, 2, 0],
      [1, 0, 2]],
     [[5, 8, 0],
      [2, 7, 0]],
     [[2, 1, 9],
      [4, -3, 32]]]
)


In [60]:
print(a.shape)

(4, 3, 2)


In [61]:
print(b.shape)

(4, 2, 3)


In [62]:
print(tf.linalg.matmul(a, b))

tf.Tensor(
[[[  1   2   0]
  [  5   9  -1]
  [  0   1   1]]

 [[  2   0   4]
  [  9   2  -2]
  [ 23   4   6]]

 [[  9  22   0]
  [  2   7   0]
  [  7  15   0]]

 [[  4   2  18]
  [  6  -2  41]
  [ -4   3 -32]]], shape=(4, 3, 3), dtype=int32)


In [63]:
print(a[0], b[0])

tf.Tensor(
[[ 1  0]
 [ 2  1]
 [ 3 -1]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [64]:
tf.linalg.band_part(a, 0, 0)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  0],
        [ 0,  1],
        [ 0,  0]],

       [[ 0,  0],
        [ 0, -1],
        [ 0,  0]],

       [[ 1,  0],
        [ 0,  1],
        [ 0,  0]],

       [[ 2,  0],
        [ 0,  1],
        [ 0,  0]]], dtype=int32)>

In [65]:
a = tf.constant ([
     [2, 6, 5, 2],
     [2, -2, 2, 3],
     [1, 5, 4, 0]
])

b = tf.constant ([
     [2, 9, 0, 3, 0],
     [3, 6, 8, -2, 2],
     [1, 3, 5, 0, 1],
     [3, 0, 2, 0, 5]
])

c = tf.linalg.matmul(a, b)
print(a.shape, b.shape)
print(c.shape)
print(c)

(3, 4) (4, 5)
(3, 5)
tf.Tensor(
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]], shape=(3, 5), dtype=int32)


In [66]:
tf.einsum("ij, jk->ik", a, b)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[33, 69, 77, -6, 27],
       [ 9, 12,  0, 10, 13],
       [21, 51, 60, -7, 14]], dtype=int32)>

In [67]:
a = tf.constant ([2, 6, 5, 2])
b = tf.constant ([0, 1, 3, 2])
tf.einsum("i,j->ij", a, b)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  2,  6,  4],
       [ 0,  6, 18, 12],
       [ 0,  5, 15, 10],
       [ 0,  2,  6,  4]], dtype=int32)>

In [68]:
a = tf.constant ([2, 6, 5, 2])
b = tf.constant ([0, 1, 3, 2])
print(tf.reduce_sum(c))
print(c)

print(tf.einsum("i,j->ij", a, b))

tf.Tensor(383, shape=(), dtype=int32)
tf.Tensor(
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[ 0  2  6  4]
 [ 0  6 18 12]
 [ 0  5 15 10]
 [ 0  2  6  4]], shape=(4, 4), dtype=int32)


In [69]:
b = tf.constant([
    [2, 9, 0, 3, 0],
    [3, 6, 8, -2, 2],
    [1, 3, 5, 0, 1],
    [3, 0, 2, 0, 5]
])
tf.einsum("ij->ji", b)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 2,  3,  1,  3],
       [ 9,  6,  3,  0],
       [ 0,  8,  5,  2],
       [ 3, -2,  0,  0],
       [ 0,  2,  1,  5]], dtype=int32)>

In [70]:
import tensorflow as tf

a = tf.constant([
     [2, 6, 5, 2],
     [2, -2, 2, 3],
     [1, 5, 4, 0]
])

b = tf.constant([
     [2, 9, 0, 3, 0],
     [3, 6, 8, -2, 2],
     [1, 3, 5, 0, 1],
     [3, 0, 2, 0, 5]
])

result = tf.matmul(a, b)
print(result)


tf.Tensor(
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]], shape=(3, 5), dtype=int32)


In [71]:
print(tf.linalg.matmul(a, a, transpose_b=True))
print(a.shape)

tf.Tensor(
[[69  8 52]
 [ 8 21  0]
 [52  0 42]], shape=(3, 3), dtype=int32)
(3, 4)


In [72]:
a = tf.constant([1, 3, 4, 5, 6, 7])

In [73]:
a = tf.constant([

     [[2, 6, 5, 2],
     [2, -2, 2, 3],
     [1, 5, 4, 0]],

     [[2, 6, 5, 2],
      [2, -2, 2, 3],
      [1, 5, 4, 0]]
])
print(a.shape)

(2, 3, 4)


In [74]:
tf.expand_dims(a, axis=0)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]],

        [[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]]]], dtype=int32)>

In [75]:
tf.expand_dims(a, axis=1)

<tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
array([[[[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]]],


       [[[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]]]], dtype=int32)>

In [76]:
tf.expand_dims(a, axis=0)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]],

        [[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]]]], dtype=int32)>

In [77]:
tf.expand_dims(a, axis=2)

<tf.Tensor: shape=(2, 3, 1, 4), dtype=int32, numpy=
array([[[[ 2,  6,  5,  2]],

        [[ 2, -2,  2,  3]],

        [[ 1,  5,  4,  0]]],


       [[[ 2,  6,  5,  2]],

        [[ 2, -2,  2,  3]],

        [[ 1,  5,  4,  0]]]], dtype=int32)>

In [78]:
c = tf.expand_dims(a, axis=-1)
print(c.shape)
print(tf.squeeze(c, axis=-1))

(2, 3, 4, 1)
tf.Tensor(
[[[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]

 [[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]], shape=(2, 3, 4), dtype=int32)


In [79]:
t1 = tf.constant (
    [[1, 2, 3],
     [2, 5, 6]]
)
t2= tf.constant (
    [[7, 8, 9],
     [10, 11, 12]]
)

print(t1.shape, t2.shape)

(2, 3) (2, 3)


In [80]:
tf.reshape(t1, [6])

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 2, 5, 6], dtype=int32)>

In [81]:
tf.concat([t1, t2], axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 2,  5,  6, 10, 11, 12]], dtype=int32)>

In [82]:
tf.concat([t1, t2], axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 2,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [83]:
t1 = tf.constant([
    [[1, 2],
     [2, 3]],
    [[4, 4],
     [5, 3]]
])

t2 = tf.constant([
    [[7, 8],
     [8, 4]],
    [[2, 10],
     [15, 11]]
])

print(t1.shape, t2.shape)

(2, 2, 2) (2, 2, 2)


In [84]:
tf.stack([tf.expand_dims(t1, -1),
          tf.expand_dims(t2, -1)], axis=0)

<tf.Tensor: shape=(2, 2, 2, 2, 1), dtype=int32, numpy=
array([[[[[ 1],
          [ 2]],

         [[ 2],
          [ 3]]],


        [[[ 4],
          [ 4]],

         [[ 5],
          [ 3]]]],



       [[[[ 7],
          [ 8]],

         [[ 8],
          [ 4]]],


        [[[ 2],
          [10]],

         [[15],
          [11]]]]], dtype=int32)>

In [85]:
print(tf.concat([t1, t2], -1))

tf.Tensor(
[[[ 1  2  7  8]
  [ 2  3  8  4]]

 [[ 4  4  2 10]
  [ 5  3 15 11]]], shape=(2, 2, 4), dtype=int32)


In [86]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
print(tf.pad(t, paddings, "CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)


In [87]:
a = tf.constant([4, 5, 6, 7])
print(a[1:3])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [88]:
tf.gather(a, [0, 3, 1])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 7, 5], dtype=int32)>

In [89]:
b = tf.constant([
    [2, 9, 0, 3, 0],
    [3, 6, 8, -2, 2],
    [1, 3, 5, 0, 1],
    [3, 0, 2, 0, 5]
])

In [90]:
tf.gather(b,[3,1],axis=1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  9],
       [-2,  6],
       [ 0,  3],
       [ 0,  0]], dtype=int32)>

In [91]:
tf.gather_nd(b, [[1, 3], [2, 0]])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2,  1], dtype=int32)>

In [92]:
tf.gather_nd(b,[[1],
                [3]])

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 3,  6,  8, -2,  2],
       [ 3,  0,  2,  0,  5]], dtype=int32)>

In [93]:
tf.gather(b,[[1,3]],axis=0)

<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[ 3,  6,  8, -2,  2],
        [ 3,  0,  2,  0,  5]]], dtype=int32)>

In [94]:
a = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [95]:
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4], [5, 6]])
boolean_mask = tf.ragged.constant([[False, False, True], [False], [True, True]])

# Apply the boolean mask
masked_tensor = tf.ragged.boolean_mask(ragged_tensor, boolean_mask)

# Print the result
print(masked_tensor)

<tf.RaggedTensor [[3], [], [5, 6]]>


In [99]:
import tensorflow as tf

values = [3, 1, 4, 1, 5, 9, 2, 6]

# Using from_row_splits
print(tf.RaggedTensor.from_row_splits(values, row_splits=[0, 4, 4, 7, 8, 8]))

# Using from_row_lengths
print(tf.RaggedTensor.from_row_lengths(values, row_lengths=[4, 0, 3, 1, 0]))

# Using from_value_rowids
print(tf.RaggedTensor.from_value_rowids(values, value_rowids=[0, 0, 0, 0, 2, 2, 2, 3], nrows=5))

# Using from_row_starts
print(tf.RaggedTensor.from_row_starts(values, row_starts=[0, 4, 4, 7, 8]))

# Using from_row_limits
print(tf.RaggedTensor.from_row_limits(values, row_limits=[4, 4, 7, 8, 8]))

# Using from_uniform_row_length
print(tf.RaggedTensor.from_uniform_row_length(values, uniform_row_length=2))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1],
 [4, 1],
 [5, 9],
 [2, 6]]>


In [101]:
values = [3, 1, 4, 1, 5, 9, 2, 6, 7]

print(tf.RaggedTensor.from_uniform_row_length(values, uniform_row_length=3))

<tf.RaggedTensor [[3, 1, 4],
 [1, 5, 9],
 [2, 6, 7]]>


In [102]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]],
    values=[1, 9],
    dense_shape=[5, 6]
)

print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [104]:
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [105]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 0, 9, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

In [106]:
tensor_string = tf.constant(["i am", "a", "string"])

tensor_string

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am', b'a', b'string'], dtype=object)>

In [109]:
joined_string = tf.strings.join(tensor_string, separator=" + ")


In [110]:
print(joined_string.numpy())

b'i am + a + string'


In [111]:
x = tf.constant([1, 2, 3, 4, 5])

In [112]:
x_var = tf.Variable(x)

In [113]:
print(x, x_var)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [115]:
x_var.assign_add([5, 5, 5, 5, 5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [116]:
x_var.assign([5, 5, 5, 5, 5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 5, 5, 5, 5], dtype=int32)>